CREATE TABLE IF NOT EXISTS `fortuna_huntingwagon_cargo` (
    `adapter` VARCHAR(32) NOT NULL,
    `wagon_id` BIGINT UNSIGNED NOT NULL,
    `cargo` LONGTEXT NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`adapter`, `wagon_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
